firstname = input("Cual es tu nombre?")
lastname = input("Cual es tu apellido?")
seccion = input("Cual es tu seccion?")
sede = input("Cual es tu sede?")
print("Hola " + firstname, lastname + "Tu seccion es "+ seccion +"y tu sede es " + sede)
